export const overlaySymbols = [
    { value: 'circle', label: '⬤', unicode: '⬤', displayName: 'Circle' },
    { value: 'rightHalfBlackCircle', label: '◗', unicode: '◗', displayName: 'Filled Half Circle' },
    { value: 'outlinedCircle', label: '◯', unicode: '◯', displayName: 'Outlined Circle' },
    { value: 'blackSunWithRays', label: '☀', unicode: '☀', displayName: 'Sun' },
    { value: 'cloud', label: '☁', unicode: '☁', displayName: 'Cloud' },
    { value: 'umbrella', label: '☂', unicode: '☂', displayName: 'Umbrella' },
    { value: 'snowman', label: '☃', unicode: '☃', displayName: 'Snowman' },
    { value: 'comet', label: '☄', unicode: '☄', displayName: 'Comet' },
    { value: 'blackStar', label: '★', unicode: '★', displayName: 'Filled Star' },
    { value: 'whiteStar', label: '☆', unicode: '☆', displayName: 'Outlined Star' },
    { value: 'lightning', label: '☇', unicode: '☇', displayName: 'Lightning' },
    { value: 'thunderstorm', label: '☈', unicode: '☈', displayName: 'Thunderstorm' },
    { value: 'solar', label: '☉', unicode: '☉', displayName: 'Solar' },
    { value: 'ascendingNode', label: '☊', unicode: '☊', displayName: 'Ascending Node' },
    { value: 'descendingNode', label: '☋', unicode: '☋', displayName: 'Descending Node' },
    { value: 'conjunction', label: '☌', unicode: '☌', displayName: 'Conjunction' },
    { value: 'opposition', label: '☍', unicode: '☍', displayName: 'Opposition' },
    { value: 'blackTelephone', label: '☎', unicode: '☎', displayName: 'Filled Telephone' },
    { value: 'whiteTelephone', label: '☏', unicode: '☏', displayName: 'Outlined Telephone' },
    { value: 'ballotBox', label: '☐', unicode: '☐', displayName: 'Ballot Box' },
    { value: 'ballotBoxWithCheck', label: '☑', unicode: '☑', displayName: 'Ballot Box with Check' },
    { value: 'ballotBoxWithX', label: '☒', unicode: '☒', displayName: 'Ballot Box with X' },
    { value: 'blackUpPointingTriangle', label: '▲', unicode: '▲', displayName: 'Filled Triangle' },
    { value: 'whiteUpPointingTriangle', label: '△', unicode: '△', displayName: 'Outlined Triangle' },
    { value: 'whiteRightTriangle', label: '⊿', unicode: '⊿', displayName: 'Outlined Right Triangle' },
    { value: 'circledTriangleDown', label: '◢', unicode: '◢', displayName: 'Filled Right Triangle' },
    { value: 'circledPlus', label: '⊕', unicode: '⊕', displayName: 'Circled Plus' },
    { value: 'circledMinus', label: '⊖', unicode: '⊖', displayName: 'Circled Minus' },
    { value: 'circledSlash', label: '⊘', unicode: '⊘', displayName: 'Circled Slash' },
    { value: 'circledRing', label: '⊚', unicode: '⊚', displayName: 'Circled Ring' },
    { value: 'circledAsterisk', label: '⊛', unicode: '⊛', displayName: 'Circled Asterisk' },
    { value: 'circledEquals', label: '⊜', unicode: '⊜', displayName: 'Circled Equals' },
    { value: 'circledDot', label: '⦁', unicode: '⦁', displayName: 'Circled Dot' },
    { value: 'smallCircle', label: '◦', unicode: '◦', displayName: 'Small Circle' },
    { value: 'circledWhiteStar', label: '✪', unicode: '✪', displayName: 'Circled White Star' },
    { value: 'doubleCircledPlus', label: '⨁', unicode: '⨁', displayName: 'Double-Circled Plus' },
    { value: 'circledCross', label: '⛧', unicode: '⛧', displayName: 'Circled Cross' },
    { value: 'circledVerticalBar', label: '⦶', unicode: '⦶', displayName: 'Circled Vertical Bar' },
    { value: 'eightSpokedAsterisk', label: '✻', unicode: '✻', displayName: 'Eight Spoked Asterisk' },
    { value: 'sixSpokedAsterisk', label: '✺', unicode: '✺', displayName: 'Six Spoked Asterisk' },
    { value: 'blackLowerRightTriangle', label: '⎊', unicode: '⎊', displayName: 'Circle Triangle' },
    { value: 'blackMediumUpPointingTriangle', label: '⏶', unicode: '⏶', displayName: 'Filled Smaller Triangle' },
    { value: 'blackFullBlock', label: '█', unicode: '█', displayName: 'Full Block' },
    { value: 'upperHalfBlock', label: '▀', unicode: '▀', displayName: 'Upper Half Block' },
    { value: 'leftHalfBlock', label: '▌', unicode: '▌', displayName: 'Left Half Block' },
    { value: 'blackSquare', label: '■', unicode: '■', displayName: 'Filled Square' },
    { value: 'whiteSquare', label: '□', unicode: '□', displayName: 'Outlined Square' },
    { value: 'blackSmallSquare', label: '▪', unicode: '▪', displayName: 'Filled Small Square' },
    { value: 'whiteSmallSquare', label: '▫', unicode: '▫', displayName: 'Outlined Small Square' },
    { value: 'blackMediumSquare', label: '◼', unicode: '◼', displayName: 'Filled Medium Square' },
    { value: 'whiteMediumSquare', label: '◻', unicode: '◻', displayName: 'Outlined Medium Square' },
    { value: 'blackPentagon', label: '⬟', unicode: '⬟', displayName: 'Filled Pentagon' },
    { value: 'whitePentagon', label: '⬠', unicode: '⬠', displayName: 'Outlined Pentagon' },
    { value: 'blackHexagon', label: '⬢', unicode: '⬢', displayName: 'Filled Hexagon' },
    { value: 'whiteHexagon', label: '⬡', unicode: '⬡', displayName: 'Outlined Hexagon' },
    { value: 'whitePentagonShape', label: '⬬', unicode: '⬬', displayName: 'Filled Horizontal Ellipse Shape' },
    { value: 'blackHexagonShape', label: '⬭', unicode: '⬭', displayName: 'Outlined Horizontal Ellipse Shape' },
    { value: 'whiteHexagonShape', label: '⬮', unicode: '⬮', displayName: 'Filled Vertical Ellipse Shape' },
    { value: 'blackOctagonShape', label: '⬯', unicode: '⬯', displayName: 'Outlined Vertical Ellipse Shape' },
    { value: 'whiteOctagonShape', label: '⬰', unicode: '⬰', displayName: 'Arrow with Small Circle' },
    { value: 'blackOctagon', label: '⯃', unicode: '⯃', displayName: 'Filled Octagon' },
    { value: 'blackChevron', label: '⩔', unicode: '⩔', displayName: 'Outlined Chevron' },
    { value: 'whiteChevron', label: '⩕', unicode: '⩕', displayName: 'Outlined Chevron' },
    { value: 'blackLozenge', label: '◆', unicode: '◆', displayName: 'Filled Lozenge' },
    { value: 'whiteLozenge', label: '◇', unicode: '◇', displayName: 'Outlined Lozenge' },
    { value: 'blackArrowHead', label: '➤', unicode: '➤', displayName: 'Rightwards Arrow' },
    { value: 'whiteCurvedArrow', label: '➥', unicode: '➥', displayName: 'Curved Downwards/Rightwards Arrow' },
    { value: 'whiteArrow', label: '⇧', unicode: '⇧', displayName: 'Outlined Arrow' },
    { value: 'blackArrow', label: '➔', unicode: '➔', displayName: 'Filled Arrow' },
    { value: 'blackUpDownArrow', label: '↕', unicode: '↕', displayName: 'Two-Sided Arrow' },
    { value: 'rightArrowCurvingLeft', label: '↩', unicode: '↩', displayName: 'Right Arrow Curving Left' },
    { value: 'rightArrowCurvingUp', label: '⤴', unicode: '⤴', displayName: 'Right Arrow Curving Up' },
    { value: 'leftArrowCurvingRight', label: '↪', unicode: '↪', displayName: 'Left Arrow Curving Right' },
    { value: 'leftArrowCurvingDown', label: '⤵', unicode: '⤵', displayName: 'Left Arrow Curving Down' },
    { value: 'blackFourPointedStar', label: '✦', unicode: '✦', displayName: 'Filled Four Pointed Star' },
    { value: 'whiteFourPointedStar', label: '✧', unicode: '✧', displayName: 'Outlined Four Pointed Star' },
    { value: 'blackStarSixPointed', label: '✶', unicode: '✶', displayName: 'Six Pointed Star' },
    { value: 'mediumFourPointedPinwheelStar', label: '🟇', unicode: '🟇', displayName: 'Four Pointed Pinwheel Star' },
    { value: 'whiteStarSixPointed', label: '✵', unicode: '✵', displayName: 'Eight Pointed Pinwheel Star' },
    { value: 'blackEightPointedStar', label: '✸', unicode: '✸', displayName: 'Eight Pointed Rectilinear Star' },
    { value: 'whiteEightPointedStar', label: '✹', unicode: '✹', displayName: 'Twelve Pointed Star' },
    { value: 'blackFourDiamondStar', label: '❖', unicode: '❖', displayName: 'Four Diamond Star' },
    { value: 'diamondTick', label: '⟢', unicode: '⟢', displayName: 'Diamond with Tick' },
    { value: 'snowflake', label: '❄', unicode: '❄', displayName: 'Snowflake' },
    { value: 'saltire', label: '☓', unicode: '☓', displayName: 'Saltire' },
    { value: 'infinity', label: '∞', unicode: '∞', displayName: 'Infinity' },
    { value: 'umbrellaWithRainDrops', label: '☔', unicode: '☔', displayName: 'Umbrella with Rain Drops' },
    { value: 'hotBeverage', label: '☕', unicode: '☕', displayName: 'Coffee' },
    { value: 'crescentMoon', label: '🌙', unicode: '🌙', displayName: 'Crescent Moon' },
    { value: 'whiteShogiPiece', label: '☖', unicode: '☖', displayName: 'Outlined Shogi Piece' },
    { value: 'blackShogiPiece', label: '☗', unicode: '☗', displayName: 'Filled Shogi Piece' },
    { value: 'shamrock', label: '☘', unicode: '☘', displayName: 'Shamrock' },
    { value: 'reversedRotatedFloralHeartBullet', label: '☙', unicode: '☙', displayName: 'Reversed Rotated Floral Heart Bullet' },
    { value: 'blackLeftPointingIndex', label: '☚', unicode: '☚', displayName: 'Filled Left Pointing Index' },
    { value: 'blackRightPointingIndex', label: '☛', unicode: '☛', displayName: 'Filled Right Pointing Index' },
    { value: 'whiteLeftPointingIndex', label: '☜', unicode: '☜', displayName: 'Outlined Left Pointing Index' },
    { value: 'whiteRightPointingIndex', label: '☞', unicode: '☞', displayName: 'Outlined Pointing Index' },
    { value: 'whiteUpPointingIndex', label: '☝', unicode: '☝', displayName: 'Pointing Index' },
    { value: 'raisedHand', label: '🖑', unicode: '🖑', displayName: 'Raised Hand' },
    { value: 'skullAndCrossbones', label: '☠', unicode: '☠', displayName: 'Skull and Crossbones' },
    { value: 'pi', label: 'π', unicode: '\u03C0', displayName: 'Pi' },
    { value: 'translingual', label: '☡', unicode: '☡', displayName: 'Translingual' },
    { value: 'radioactiveSign', label: '☢', unicode: '☢', displayName: 'Radioactive Sign' },
    { value: 'biohazardSign', label: '☣', unicode: '☣', displayName: 'Biohazard Sign' },
    { value: 'mapleLeaf', label: '🍁', unicode: '🍁', displayName: 'Maple Leaf' },
    { value: 'caduceus', label: '☤', unicode: '☤', displayName: 'Caduceus' },
    { value: 'ankh', label: '☥', unicode: '☥', displayName: 'Ankh' },
    { value: 'orthodoxCross', label: '☦', unicode: '☦', displayName: 'Orthodox Cross' },
    { value: 'chiRho', label: '☧', unicode: '☧', displayName: 'Chi Rho' },
    { value: 'blackCross', label: '✚', unicode: '✚', displayName: 'Filled Cross' },
    { value: 'whiteCross', label: '✛', unicode: '✛', displayName: 'Outlined Cross' },
    { value: 'crossOfLorraine', label: '☨', unicode: '☨', displayName: 'Cross of Lorraine' },
    { value: 'crossOfJerusalem', label: '☩', unicode: '☩', displayName: 'Cross of Jerusalem' },
    { value: 'malteseCross', label: '✠', unicode: '✠', displayName: 'Maltese Cross' },
    { value: 'westSyrianCross', label: '♰', unicode: '♰', displayName: 'West Syrian Cross' },
    { value: 'eastSyrianCross', label: '♱', unicode: '♱', displayName: 'East Syrian Cross' },
    { value: 'dottedCross', label: '⁜', unicode: '⁜', displayName: 'Dotted Cross' },
    { value: 'boxDrawingsLightDiagonalCross', label: '╳', unicode: '╳', displayName: 'Box Drawings Light Diagonal Cross' },
    { value: 'squareWithOrthogonalCrosshatchFill', label: '▦', unicode: '▦', displayName: 'Square with Orthogonal Crosshatch Fill' },
    { value: 'squareWithDiagonalCrosshatchFill', label: '▩', unicode: '▩', displayName: 'Square with Diagonal Crosshatch Fill' },
    { value: 'crossingLanes', label: '⛌', unicode: '⛌', displayName: 'Crossing Lanes' },
    { value: 'circledCrossingLanes', label: '⛒', unicode: '⛒', displayName: 'Circled Crossing Lanes' },
    { value: 'blackCrossOnShield', label: '⛨', unicode: '⛨', displayName: 'Cross On Shield' },
    { value: 'shield', label: '🛡', unicode: '🛡', displayName: 'Shield'},
    { value: 'outlinedGreekCross', label: '✙', unicode: '✙', displayName: 'Outlined Greek Cross' },
    { value: 'heavyGreekCross', label: '✚', unicode: '✚', displayName: 'Heavy Greek Cross' },
    { value: 'openCentreCross', label: '✛', unicode: '✛', displayName: 'Open Centre Cross' },
    { value: 'heavyOpenCentreCross', label: '✜', unicode: '✜', displayName: 'Heavy Open Centre Cross' },
    { value: 'latinCross', label: '✝', unicode: '✝', displayName: 'Latin Cross' },
    { value: 'shadowedWhiteLatinCross', label: '✞', unicode: '✞', displayName: 'Shadowed Latin Cross' },
    { value: 'outlinedLatinCross', label: '✟', unicode: '✟', displayName: 'Outlined Latin Cross' },
    { value: 'starAndCrescent', label: '☪', unicode: '☪', displayName: 'Star and Crescent' },
    { value: 'blackMoonLilith', label: '⚸', unicode: '⚸', displayName: 'Black Moon Lilith' },
    { value: 'kharoshthiPunctuationCrescentBar', label: '𐩓', unicode: '𐩓', displayName: 'Kharoshthi Punctuation Crescent Bar' },
    { value: 'starOfDavid', label: '✡', unicode: '✡', displayName: 'Star of David' },
    { value: 'outlinedWhiteStar', label: '⚝', unicode: '\u269D', displayName: 'Outlined Moroccan Star' },
    { value: 'farsiSymbol', label: '☫', unicode: '☫', displayName: 'Farsi Symbol' },
    { value: 'khanda', label: '☬', unicode: '☬', displayName: 'Khanda' },
    { value: 'hammerAndSickle', label: '☭', unicode: '☭', displayName: 'Hammer and Sickle' },
    { value: 'peaceSymbol', label: '☮', unicode: '☮', displayName: 'Peace Symbol' },
    { value: 'yinYang', label: '☯', unicode: '☯', displayName: 'Yin Yang' },
    { value: 'anchor', label: '⚓', unicode: '⚓', displayName: 'Anchor' },
    { value: 'atomSymbol', label: '⚛', unicode: '⚛', displayName: 'Atom Symbol' },
    { value: 'gear', label: '⚙', unicode: '⚙', displayName: 'Gear' },
    { value: 'hammer', label: '⚒', unicode: '⚒', displayName: 'Hammer' },
    { value: 'balanceScale', label: '⚖', unicode: '⚖', displayName: 'Balance Scale' },
    { value: 'medicalSymbol', label: '⚕', unicode: '⚕', displayName: 'Medical Symbol' },
    { value: 'radioactive', label: '☢', unicode: '☢', displayName: 'Radioactive' },
    { value: 'checkMark', label: '✔', unicode: '✔', displayName: 'Check Mark' },
    { value: 'crossMark', label: '✖', unicode: '✖', displayName: 'Cross Mark' },
    { value: 'recyclingSymbol', label: '♻', unicode: '♻', displayName: 'Recycling Symbol' },
    { value: 'trigramForHeaven', label: '☰', unicode: '☰', displayName: 'Trigram for Heaven' },
    { value: 'trigramForLake', label: '☱', unicode: '☱', displayName: 'Trigram for Lake' },
    { value: 'trigramForFire', label: '☲', unicode: '☲', displayName: 'Trigram for Fire' },
    { value: 'trigramForThunder', label: '☳', unicode: '☳', displayName: 'Trigram for Thunder' },
    { value: 'trigramForWind', label: '☴', unicode: '☴', displayName: 'Trigram for Wind' },
    { value: 'trigramForWater', label: '☵', unicode: '☵', displayName: 'Trigram for Water' },
    { value: 'trigramForMountain', label: '☶', unicode: '☶', displayName: 'Trigram for Mountain' },
    { value: 'trigramForEarth', label: '☷', unicode: '☷', displayName: 'Trigram for Earth' },
    { value: 'wheelOfDharma', label: '☸', unicode: '☸', displayName: 'Wheel of Dharma' },
    { value: 'whiteFrowningFace', label: '☹', unicode: '☹', displayName: 'Outlined Frowning Face' },
    { value: 'whiteSmilingFace', label: '☺', unicode: '☺', displayName: 'Outlined Smiling Face' },
    { value: 'blackSmilingFace', label: '☻', unicode: '☻', displayName: 'Filled Smiling Face' },
    { value: 'whiteSunWithRays', label: '☼', unicode: '☼', displayName: 'Outlined Sun with Rays' },
    { value: 'sunWithFace', label: '🌞', unicode: '🌞', displayName: 'Sun with Face' },
    { value: 'moonWithFace', label: '🌝', unicode: '🌝', displayName: 'Moon with Face' },
    { value: 'firstQuarterMoon', label: '☽', unicode: '☽', displayName: 'First Quarter Moon' },
    { value: 'lastQuarterMoon', label: '☾', unicode: '☾', displayName: 'Last Quarter Moon' },
    { value: 'mercury', label: '☿', unicode: '☿', displayName: 'Mercury' },
    { value: 'femaleSign', label: '♀', unicode: '♀', displayName: 'Female Sign' },
    { value: 'earth', label: '♁', unicode: '♁', displayName: 'Earth' },
    { value: 'maleSign', label: '♂', unicode: '♂', displayName: 'Male Sign' },
    { value: 'jupiter', label: '♃', unicode: '♃', displayName: 'Jupiter' },
    { value: 'saturn', label: '♄', unicode: '♄', displayName: 'Saturn' },
    { value: 'uranus', label: '♅', unicode: '♅', displayName: 'Uranus' },
    { value: 'neptune', label: '♆', unicode: '♆', displayName: 'Neptune' },
    { value: 'tridentEmblem', label: '🔱', unicode: '🔱', displayName: 'Trident Emblem' },
    { value: 'fleurDeLis', label: '⚜', unicode: '⚜', displayName: 'Fleur-De-Lis' },
    { value: 'whiteChessKing', label: '♔', unicode: '♔', displayName: 'Outlined Chess King' },
    { value: 'whiteChessQueen', label: '♕', unicode: '♕', displayName: 'Outlined Chess Queen' },
    { value: 'whiteChessRook', label: '♖', unicode: '♖', displayName: 'Outlined Chess Rook' },
    { value: 'whiteChessBishop', label: '♗', unicode: '♗', displayName: 'Outlined Chess Bishop' },
    { value: 'whiteChessKnight', label: '♘', unicode: '♘', displayName: 'Outlined Chess Knight' },
    { value: 'whiteChessPawn', label: '♙', unicode: '♙', displayName: 'Outlined Chess Pawn' },
    { value: 'blackChessKing', label: '♚', unicode: '♚', displayName: 'Filled Chess King' },
    { value: 'blackChessQueen', label: '♛', unicode: '♛', displayName: 'Filled Chess Queen' },
    { value: 'blackChessRook', label: '♜', unicode: '♜', displayName: 'Filled Chess Rook' },
    { value: 'blackChessBishop', label: '♝', unicode: '♝', displayName: 'Filled Chess Bishop' },
    { value: 'blackChessKnight', label: '♞', unicode: '♞', displayName: 'Filled Chess Knight' },
    { value: 'blackChessPawn', label: '♟', unicode: '♟', displayName: 'Filled Chess Pawn' },
    { value: 'blackSpadeSuit', label: '♠', unicode: '♠', displayName: 'Filled Spade Suit' },
    { value: 'whiteHeartSuit', label: '♡', unicode: '♡', displayName: 'Outlined Heart Suit' },
    { value: 'whiteDiamondSuit', label: '♢', unicode: '♢', displayName: 'Outlined Diamond Suit' },
    { value: 'blackClubSuit', label: '♣', unicode: '♣', displayName: 'Filled Club Suit' },
    { value: 'whiteSpadeSuit', label: '♤', unicode: '♤', displayName: 'Outlined Spade Suit' },
    { value: 'blackHeartSuit', label: '♥', unicode: '♥', displayName: 'Filled Heart Suit' },
    { value: 'blackDiamondSuit', label: '♦', unicode: '♦', displayName: 'Filled Diamond Suit' },
    { value: 'whiteClubSuit', label: '♧', unicode: '♧', displayName: 'Outlined Club Suit' },
    { value: 'blackDiamondShape', label: '⬥', unicode: '⬥', displayName: 'Filled Diamond Shape' },
    { value: 'whiteDiamondShape', label: '⬦', unicode: '⬦', displayName: 'Outlined Diamond Shape' },
    { value: 'hotSprings', label: '♨', unicode: '♨', displayName: 'Hot Springs' },
    { value: 'quarterNote', label: '♩', unicode: '♩', displayName: 'Quarter Note' },
    { value: 'eighthNote', label: '♪', unicode: '♪', displayName: 'Eighth Note' },
    { value: 'beamedEighthNotes', label: '♫', unicode: '♫', displayName: 'Beamed Eighth Notes' },
    { value: 'beamedSixteenthNotes', label: '♬', unicode: '♬', displayName: 'Beamed Sixteenth Notes' },
    { value: 'musicFlatSign', label: '♭', unicode: '♭', displayName: 'Music Flat Sign' },
    { value: 'musicNaturalSign', label: '♮', unicode: '♮', displayName: 'Music Natural Sign' },
    { value: 'musicSharpSign', label: '♯', unicode: '♯', displayName: 'Music Sharp Sign' },
    { value: 'pluto', label: '♇', unicode: '♇', displayName: 'Pluto' },
    { value: 'aries', label: '♈', unicode: '♈', displayName: 'Aries' },
    { value: 'taurus', label: '♉', unicode: '♉', displayName: 'Taurus' },
    { value: 'gemini', label: '♊', unicode: '♊', displayName: 'Gemini' },
    { value: 'cancer', label: '♋', unicode: '♋', displayName: 'Cancer' },
    { value: 'leo', label: '♌', unicode: '♌', displayName: 'Leo' },
    { value: 'virgo', label: '♍', unicode: '♍', displayName: 'Virgo' },
    { value: 'libra', label: '♎', unicode: '♎', displayName: 'Libra' },
    { value: 'scorpius', label: '♏', unicode: '♏', displayName: 'Scorpius' },
    { value: 'sagittarius', label: '♐', unicode: '♐', displayName: 'Sagittarius' },
    { value: 'capricorn', label: '♑', unicode: '♑', displayName: 'Capricorn' },
    { value: 'aquarius', label: '♒', unicode: '♒', displayName: 'Aquarius' },
    { value: 'pisces', label: '♓', unicode: '♓', displayName: 'Pisces' },
    { value: 'hourglass', label: '⌛', unicode: '⌛', displayName: 'Hourglass' },
    { value: 'hourglassSand', label: '⏳', unicode: '⏳', displayName: 'Hourglass Flowing Sand' },
    { value: 'lightBulb', label: '💡', unicode: '💡', displayName: 'Light Bulb' },
    { value: 'droplet', label: '💧', unicode: '💧', displayName: 'Droplet' },
    { value: 'tree', label: '🌲', unicode: '🌲', displayName: 'Tree' },
    { value: 'wheelchairSymbol', label: '♿', unicode: '♿', displayName: 'Wheelchair Symbol' },
];