export const overlaySymbols = [
    { value: 'circle', label: '⬤', unicode: '⬤', displayName: 'Circle' },
    { value: 'blackSunWithRays', label: '☀', unicode: '☀', displayName: 'Sun' },
    { value: 'cloud', label: '☁', unicode: '☁', displayName: 'Cloud' },
    { value: 'umbrella', label: '☂', unicode: '☂', displayName: 'Umbrella' },
    { value: 'snowman', label: '☃', unicode: '☃', displayName: 'Snowman' },
    { value: 'comet', label: '☄', unicode: '☄', displayName: 'Comet' },
    { value: 'blackStar', label: '★', unicode: '★', displayName: 'Filled Star' },
    { value: 'whiteStar', label: '☆', unicode: '☆', displayName: 'Outlined Star' },
    { value: 'lightning', label: '☇', unicode: '☇', displayName: 'Lightning' },
    { value: 'thunderstorm', label: '☈', unicode: '☈', displayName: 'Thunderstorm' },
    { value: 'sun', label: '☉', unicode: '☉', displayName: 'Sun' },
    { value: 'ascendingNode', label: '☊', unicode: '☊', displayName: 'Ascending Node' },
    { value: 'descendingNode', label: '☋', unicode: '☋', displayName: 'Descending Node' },
    { value: 'conjunction', label: '☌', unicode: '☌', displayName: 'Conjunction' },
    { value: 'opposition', label: '☍', unicode: '☍', displayName: 'Opposition' },
    { value: 'blackTelephone', label: '☎', unicode: '☎', displayName: 'Filled Telephone' },
    { value: 'whiteTelephone', label: '☏', unicode: '☏', displayName: 'Outlined Telephone' },
    { value: 'ballotBox', label: '☐', unicode: '☐', displayName: 'Ballot Box' },
    { value: 'ballotBoxWithCheck', label: '☑', unicode: '☑', displayName: 'Ballot Box with Check' },
    { value: 'ballotBoxWithX', label: '☒', unicode: '☒', displayName: 'Ballot Box with X' },
    { value: 'blackUpPointingTriangle', label: '▲', unicode: '▲', displayName: 'Filled Triangle' },
    { value: 'whiteUpPointingTriangle', label: '△', unicode: '△', displayName: 'Outlined Triangle' },
    { value: 'blackFullBlock', label: '█', unicode: '█', displayName: 'Full Block' },
    { value: 'upperHalfBlock', label: '▀', unicode: '▀', displayName: 'Upper Half Block' },
    { value: 'leftHalfBlock', label: '▌', unicode: '▌', displayName: 'Left Half Block' },
    { value: 'blackSquare', label: '■', unicode: '■', displayName: 'Filled Square' },
    { value: 'whiteSquare', label: '□', unicode: '□', displayName: 'Outlined Square' },
    { value: 'blackSmallSquare', label: '▪', unicode: '▪', displayName: 'Filled Small Square' },
    { value: 'whiteSmallSquare', label: '▫', unicode: '▫', displayName: 'Outlined Small Square' },
    { value: 'blackMediumSquare', label: '◼', unicode: '◼', displayName: 'Filled Medium Square' },
    { value: 'whiteMediumSquare', label: '◻', unicode: '◻', displayName: 'Outlined Medium Square' },
    { value: 'saltire', label: '☓', unicode: '☓', displayName: 'Saltire' },
    { value: 'umbrellaWithRainDrops', label: '☔', unicode: '☔', displayName: 'Umbrella with Rain Drops' },
    { value: 'hotBeverage', label: '☕', unicode: '☕', displayName: 'Hot Beverage' },
    { value: 'whiteShogiPiece', label: '☖', unicode: '☖', displayName: 'Outlined Shogi Piece' },
    { value: 'blackShogiPiece', label: '☗', unicode: '☗', displayName: 'Filled Shogi Piece' },
    { value: 'shamrock', label: '☘', unicode: '☘', displayName: 'Shamrock' },
    { value: 'reversedRotatedFloralHeartBullet', label: '☙', unicode: '☙', displayName: 'Reversed Rotated Floral Heart Bullet' },
    { value: 'blackLeftPointingIndex', label: '☚', unicode: '☚', displayName: 'Filled Left Pointing Index' },
    { value: 'blackRightPointingIndex', label: '☛', unicode: '☛', displayName: 'Filled Right Pointing Index' },
    { value: 'whiteLeftPointingIndex', label: '☜', unicode: '☜', displayName: 'Outlined Left Pointing Index' },
    { value: 'whiteUpPointingIndex', label: '☝', unicode: '☝', displayName: 'Outlined Up Pointing Index' },
    { value: 'whiteRightPointingIndex', label: '☞', unicode: '☞', displayName: 'Outlined Right Pointing Index' },
    { value: 'whiteDownPointingIndex', label: '☟', unicode: '☟', displayName: 'Outlined Down Pointing Index' },
    { value: 'skullAndCrossbones', label: '☠', unicode: '☠', displayName: 'Skull and Crossbones' },
    { value: 'cautionSign', label: '☡', unicode: '☡', displayName: 'Caution Sign' },
    { value: 'radioactiveSign', label: '☢', unicode: '☢', displayName: 'Radioactive Sign' },
    { value: 'biohazardSign', label: '☣', unicode: '☣', displayName: 'Biohazard Sign' },
    { value: 'caduceus', label: '☤', unicode: '☤', displayName: 'Caduceus' },
    { value: 'ankh', label: '☥', unicode: '☥', displayName: 'Ankh' },
    { value: 'orthodoxCross', label: '☦', unicode: '☦', displayName: 'Orthodox Cross' },
    { value: 'chiRho', label: '☧', unicode: '☧', displayName: 'Chi Rho' },
    { value: 'crossOfLorraine', label: '☨', unicode: '☨', displayName: 'Cross of Lorraine' },
    { value: 'crossOfJerusalem', label: '☩', unicode: '☩', displayName: 'Cross of Jerusalem' },
    { value: 'starAndCrescent', label: '☪', unicode: '☪', displayName: 'Star and Crescent' },
    { value: 'farsiSymbol', label: '☫', unicode: '☫', displayName: 'Farsi Symbol' },
    { value: 'khanda', label: '☬', unicode: '☬', displayName: 'Khanda' },
    { value: 'hammerAndSickle', label: '☭', unicode: '☭', displayName: 'Hammer and Sickle' },
    { value: 'peaceSymbol', label: '☮', unicode: '☮', displayName: 'Peace Symbol' },
    { value: 'yinYang', label: '☯', unicode: '☯', displayName: 'Yin Yang' },
    { value: 'trigramForHeaven', label: '☰', unicode: '☰', displayName: 'Trigram for Heaven' },
    { value: 'trigramForLake', label: '☱', unicode: '☱', displayName: 'Trigram for Lake' },
    { value: 'trigramForFire', label: '☲', unicode: '☲', displayName: 'Trigram for Fire' },
    { value: 'trigramForThunder', label: '☳', unicode: '☳', displayName: 'Trigram for Thunder' },
    { value: 'trigramForWind', label: '☴', unicode: '☴', displayName: 'Trigram for Wind' },
    { value: 'trigramForWater', label: '☵', unicode: '☵', displayName: 'Trigram for Water' },
    { value: 'trigramForMountain', label: '☶', unicode: '☶', displayName: 'Trigram for Mountain' },
    { value: 'trigramForEarth', label: '☷', unicode: '☷', displayName: 'Trigram for Earth' },
    { value: 'wheelOfDharma', label: '☸', unicode: '☸', displayName: 'Wheel of Dharma' },
    { value: 'whiteFrowningFace', label: '☹', unicode: '☹', displayName: 'Outlined Frowning Face' },
    { value: 'whiteSmilingFace', label: '☺', unicode: '☺', displayName: 'Outlined Smiling Face' },
    { value: 'blackSmilingFace', label: '☻', unicode: '☻', displayName: 'Filled Smiling Face' },
    { value: 'whiteSunWithRays', label: '☼', unicode: '☼', displayName: 'Outlined Sun with Rays' },
    { value: 'firstQuarterMoon', label: '☽', unicode: '☽', displayName: 'First Quarter Moon' },
    { value: 'lastQuarterMoon', label: '☾', unicode: '☾', displayName: 'Last Quarter Moon' },
    { value: 'mercury', label: '☿', unicode: '☿', displayName: 'Mercury' },
    { value: 'femaleSign', label: '♀', unicode: '♀', displayName: 'Female Sign' },
    { value: 'earth', label: '♁', unicode: '♁', displayName: 'Earth' },
    { value: 'maleSign', label: '♂', unicode: '♂', displayName: 'Male Sign' },
    { value: 'jupiter', label: '♃', unicode: '♃', displayName: 'Jupiter' },
    { value: 'saturn', label: '♄', unicode: '♄', displayName: 'Saturn' },
    { value: 'uranus', label: '♅', unicode: '♅', displayName: 'Uranus' },
    { value: 'neptune', label: '♆', unicode: '♆', displayName: 'Neptune' },
    { value: 'pluto', label: '♇', unicode: '♇', displayName: 'Pluto' },
    { value: 'aries', label: '♈', unicode: '♈', displayName: 'Aries' },
    { value: 'taurus', label: '♉', unicode: '♉', displayName: 'Taurus' },
    { value: 'gemini', label: '♊', unicode: '♊', displayName: 'Gemini' },
    { value: 'cancer', label: '♋', unicode: '♋', displayName: 'Cancer' },
    { value: 'leo', label: '♌', unicode: '♌', displayName: 'Leo' },
    { value: 'virgo', label: '♍', unicode: '♍', displayName: 'Virgo' },
    { value: 'libra', label: '♎', unicode: '♎', displayName: 'Libra' },
    { value: 'scorpius', label: '♏', unicode: '♏', displayName: 'Scorpius' },
    { value: 'sagittarius', label: '♐', unicode: '♐', displayName: 'Sagittarius' },
    { value: 'capricorn', label: '♑', unicode: '♑', displayName: 'Capricorn' },
    { value: 'aquarius', label: '♒', unicode: '♒', displayName: 'Aquarius' },
    { value: 'pisces', label: '♓', unicode: '♓', displayName: 'Pisces' },
    { value: 'whiteChessKing', label: '♔', unicode: '♔', displayName: 'Outlined Chess King' },
    { value: 'whiteChessQueen', label: '♕', unicode: '♕', displayName: 'Outlined Chess Queen' },
    { value: 'whiteChessRook', label: '♖', unicode: '♖', displayName: 'Outlined Chess Rook' },
    { value: 'whiteChessBishop', label: '♗', unicode: '♗', displayName: 'Outlined Chess Bishop' },
    { value: 'whiteChessKnight', label: '♘', unicode: '♘', displayName: 'Outlined Chess Knight' },
    { value: 'whiteChessPawn', label: '♙', unicode: '♙', displayName: 'Outlined Chess Pawn' },
    { value: 'blackChessKing', label: '♚', unicode: '♚', displayName: 'Filled Chess King' },
    { value: 'blackChessQueen', label: '♛', unicode: '♛', displayName: 'Filled Chess Queen' },
    { value: 'blackChessRook', label: '♜', unicode: '♜', displayName: 'Filled Chess Rook' },
    { value: 'blackChessBishop', label: '♝', unicode: '♝', displayName: 'Filled Chess Bishop' },
    { value: 'blackChessKnight', label: '♞', unicode: '♞', displayName: 'Filled Chess Knight' },
    { value: 'blackChessPawn', label: '♟', unicode: '♟', displayName: 'Filled Chess Pawn' },
    { value: 'blackSpadeSuit', label: '♠', unicode: '♠', displayName: 'Filled Spade Suit' },
    { value: 'whiteHeartSuit', label: '♡', unicode: '♡', displayName: 'Outlined Heart Suit' },
    { value: 'whiteDiamondSuit', label: '♢', unicode: '♢', displayName: 'Outlined Diamond Suit' },
    { value: 'blackClubSuit', label: '♣', unicode: '♣', displayName: 'Filled Club Suit' },
    { value: 'whiteSpadeSuit', label: '♤', unicode: '♤', displayName: 'Outlined Spade Suit' },
    { value: 'blackHeartSuit', label: '♥', unicode: '♥', displayName: 'Filled Heart Suit' },
    { value: 'blackDiamondSuit', label: '♦', unicode: '♦', displayName: 'Filled Diamond Suit' },
    { value: 'whiteClubSuit', label: '♧', unicode: '♧', displayName: 'Outlined Club Suit' },
    { value: 'hotSprings', label: '♨', unicode: '♨', displayName: 'Hot Springs' },
    { value: 'quarterNote', label: '♩', unicode: '♩', displayName: 'Quarter Note' },
    { value: 'eighthNote', label: '♪', unicode: '♪', displayName: 'Eighth Note' },
    { value: 'beamedEighthNotes', label: '♫', unicode: '♫', displayName: 'Beamed Eighth Notes' },
    { value: 'beamedSixteenthNotes', label: '♬', unicode: '♬', displayName: 'Beamed Sixteenth Notes' },
    { value: 'musicFlatSign', label: '♭', unicode: '♭', displayName: 'Music Flat Sign' },
    { value: 'musicNaturalSign', label: '♮', unicode: '♮', displayName: 'Music Natural Sign' },
    { value: 'musicSharpSign', label: '♯', unicode: '♯', displayName: 'Music Sharp Sign' },
    { value: 'westSyrianCross', label: '♰', unicode: '♰', displayName: 'West Syrian Cross' },
    { value: 'eastSyrianCross', label: '♱', unicode: '♱', displayName: 'East Syrian Cross' },
];
